/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2023-06-08 07:44:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/include/config.jsp", Long.valueOf(1683533443000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1527726294253L));
    _jspx_dependants.put("jar:file:/C:/JaeYun/work-space/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mall/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/include/header.jsp", Long.valueOf(1686210237947L));
    _jspx_dependants.put("jar:file:/C:/JaeYun/work-space/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mall/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("    <meta name=\"generator\" content=\"Hugo 0.101.0\">\r\n");
      out.write("    <title>Mall</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/4.6/examples/pricing/\">\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"https://getbootstrap.com/docs/4.6/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" crossorigin=\"anonymous\">\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"https://getbootstrap.com/docs/4.6/examples/pricing/pricing.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons \r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"/docs/4.6/assets/img/favicons/apple-touch-icon.png\" sizes=\"180x180\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/4.6/assets/img/favicons/favicon-32x32.png\" sizes=\"32x32\" type=\"image/png\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/4.6/assets/img/favicons/favicon-16x16.png\" sizes=\"16x16\" type=\"image/png\">\r\n");
      out.write("<link rel=\"manifest\" href=\"/docs/4.6/assets/img/favicons/manifest.json\">\r\n");
      out.write("<link rel=\"mask-icon\" href=\"/docs/4.6/assets/img/favicons/safari-pinned-tab.svg\" color=\"#563d7c\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/4.6/assets/img/favicons/favicon.ico\">\r\n");
      out.write("<meta name=\"msapplication-config\" content=\"/docs/4.6/assets/img/favicons/browserconfig.xml\">\r\n");
      out.write("-->\r\n");
      out.write("<meta name=\"theme-color\" content=\"#563d7c\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      .bd-placeholder-img {\r\n");
      out.write("        font-size: 1.125rem;\r\n");
      out.write("        text-anchor: middle;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        -moz-user-select: none;\r\n");
      out.write("        -ms-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @media (min-width: 768px) {\r\n");
      out.write("        .bd-placeholder-img-lg {\r\n");
      out.write("          font-size: 3.5rem;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("body {\r\n");
      out.write("  background: #CBC0D3;\r\n");
      out.write("}\r\n");
      out.write("    .input-form {\r\n");
      out.write("      max-width: 680px;\r\n");
      out.write("\r\n");
      out.write("      margin-top: 80px;\r\n");
      out.write("      padding: 32px;\r\n");
      out.write("\r\n");
      out.write("      background: #EAC7CC;\r\n");
      out.write("      -webkit-border-radius: 10px;\r\n");
      out.write("      -moz-border-radius: 10px;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      -webkit-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("      -moz-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);\r\n");
      out.write("      box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15)\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t@import url('https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@200;500;600;700&display=swap');\r\n");
      out.write("\t\n");
      out.write("\t.d-flex {\r\n");
      out.write("\t\tfont-family: 'Noto Serif KR', serif;\r\n");
      out.write("\t\tfont-weight: 200;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\ta.my-0 {\r\n");
      out.write("\t\tfont-weight: 700;\r\n");
      out.write("\t\tfont-size: 1.5em;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\ta {\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tspan {\r\n");
      out.write("\t\tmargin: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav {\r\n");
      out.write("\t\tmargin-left: 20px;\r\n");
      out.write("\t}\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"swiper-slide pop2 show\" data-time-start=\"2023/02/27 00:00:00\" data-time-end=\"2025/03/01 23:59:59\" style=\"background: #000000; margin: 100%; padding: 100%; text-align: center; text-decoration: none;\"><a href=\"/member/join\"><span style=\"color: #ffffff;\">신규회원 무료배송</span></a></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm\">\r\n");
      out.write("  <a class=\"my-0 mr-md-auto font-weight-normal text-dark\" href=\"/\">FromHearts</a>\r\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <nav class=\"my-2 my-md-0 mr-md-3\">\r\n");
      out.write("    <!-- 로그인 이전 표시 -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <!--  로그인 이후 표시 -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"/member/mypage\">Mypage</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"#\">Order</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"/cart/cart_list\">Cart</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("   <div class=\"input-form-backgroud row\">\r\n");
      out.write("      <div class=\"input-form col-md-12 mx-auto\">\r\n");
      out.write("        <h4 class=\"mb-3\">회원가입</h4>\r\n");
      out.write("        <form class=\"validation-form\" id=\"joinForm\" method=\"post\" action=\"/member/join\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4 mb-3\">\r\n");
      out.write("              <label for=\"mbsp_id\">아이디</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"mbsp_id\" id=\"mbsp_id\" placeholder=\"아이디는 8~15자 이내 입력\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 mb-3\">\r\n");
      out.write("              <label for=\"mbsp_idcheck\">아이디</label>\r\n");
      out.write("              <button type=\"button\" id=\"btn_IdCheck\" class=\"btn btn-primary\">ID Check</button>              \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-5 mb-3\">\r\n");
      out.write("              <label for=\"mbsp_name\">이름</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"mbsp_name\" id=\"mbsp_name\" placeholder=\"이름을 입력\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("              <label for=\"mbsp_password\">비밀번호</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"mbsp_password\" id=\"mbsp_password\" placeholder=\"비밀번호 입력\">\r\n");
      out.write(" \t\t\t</div>\r\n");
      out.write("            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("              <label for=\"mbsp_repassword\">비밀번호확인</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"mbsp_repassword\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\t\t <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4 mb-3\">\r\n");
      out.write("            <label for=\"mbsp_email\">이메일</label>\r\n");
      out.write("            <input type=\"email\" class=\"form-control\" name=\"mbsp_email\" id=\"mbsp_email\" placeholder=\"you@example.com\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 mb-3\">\r\n");
      out.write("            <label for=\"mbsp_email_authcode\">메일인증코드</label>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" id=\"btn_authcode\">인증코드요청</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-2 mb-3\">\r\n");
      out.write("            <label for=\"email\">인증코드</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"email_auth_code\" placeholder=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 mb-3\">\r\n");
      out.write("            <label for=\"mbsp_mailconfirm\">메일인증확인</label>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\" id=\"btn_confirmAuthcode\">인증확인</button>\r\n");
      out.write("          </div>\r\n");
      out.write("         </div> \r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-2 mb-3\">\r\n");
      out.write("            <label for=\"sample2_postcode\">우편번호</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"mbsp_zipcode\" id=\"sample2_postcode\">\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-3 mb-3\">\r\n");
      out.write("            <label for=\"email\">우편버튼</label>\r\n");
      out.write("            <button type=\"button\" onclick=\"sample2_execDaumPostcode()\" class=\"btn btn-primary\">우편번호 찾기</button>\r\n");
      out.write("          </div>\r\n");
      out.write("\t\t \r\n");
      out.write("          <div class=\"col-md-7 mb-3\">\r\n");
      out.write("            <label for=\"sample2_address\">주소</label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"mbsp_addr\" id=\"sample2_address\" placeholder=\"서울특별시 강남구\">\r\n");
      out.write("          </div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12 mb-3\">\r\n");
      out.write("            <label for=\"sample2_detailAddress\">상세주소<span class=\"text-muted\">&nbsp;(필수 아님)</span></label>\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"mbsp_deaddr\" id=\"sample2_detailAddress\" placeholder=\"상세주소를 입력해주세요.\">\r\n");
      out.write("            <input type=\"hidden\" id=\"sample2_extraAddress\" placeholder=\"참고항목\">\r\n");
      out.write("          </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\t\t  <div class=\"row\">\r\n");
      out.write("\t\t  \t<div class=\"col-md-6 mb-3\">\r\n");
      out.write("              <label for=\"mbsp_phone\">연락처</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"mbsp_phone\" id=\"mbsp_phone\" placeholder=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("              <label for=\"mbsp_nick\">닉네임</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"mbsp_nick\" id=\"mbsp_nick\" placeholder=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("          \r\n");
      out.write("          <hr class=\"mb-4\">\r\n");
      out.write("          <div class=\"custom-control custom-checkbox\">\r\n");
      out.write("            <input type=\"checkbox\" class=\"custom-control-input\" name=\"mbsp_receive\" id=\"mbsp_receive\">\r\n");
      out.write("            <label class=\"custom-control-label\" for=\"mbsp_receive\">개인정보 수집 및 이용에 동의합니다.</label>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"mb-4\"></div>\r\n");
      out.write("          <button class=\"btn btn-primary btn-lg btn-block\" id=\"btn_join\" type=\"button\">가입 완료</button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- iOS에서는 position:fixed 버그가 있음, 적용하는 사이트에 맞게 position:absolute 등을 이용하여 top,left값 조정 필요 -->\r\n");
      out.write("<div id=\"layer\" style=\"display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;\">\r\n");
      out.write("<img src=\"//t1.daumcdn.net/postcode/resource/images/close.png\" id=\"btnCloseLayer\" style=\"cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1\" onclick=\"closeDaumPostcode()\" alt=\"닫기 버튼\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    // 우편번호 찾기 화면을 넣을 element\r\n");
      out.write("    var element_layer = document.getElementById('layer');\r\n");
      out.write("\r\n");
      out.write("    function closeDaumPostcode() {\r\n");
      out.write("        // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("        element_layer.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function sample2_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById(\"sample2_extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample2_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample2_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample2_address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"sample2_detailAddress\").focus();\r\n");
      out.write("\r\n");
      out.write("                // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("                // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)\r\n");
      out.write("                element_layer.style.display = 'none';\r\n");
      out.write("            },\r\n");
      out.write("            width : '100%',\r\n");
      out.write("            height : '100%',\r\n");
      out.write("            maxSuggestItems : 5\r\n");
      out.write("        }).embed(element_layer);\r\n");
      out.write("\r\n");
      out.write("        // iframe을 넣은 element를 보이게 한다.\r\n");
      out.write("        element_layer.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("        // iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.\r\n");
      out.write("        initLayerPosition();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 브라우저의 크기 변경에 따라 레이어를 가운데로 이동시키고자 하실때에는\r\n");
      out.write("    // resize이벤트나, orientationchange이벤트를 이용하여 값이 변경될때마다 아래 함수를 실행 시켜 주시거나,\r\n");
      out.write("    // 직접 element_layer의 top,left값을 수정해 주시면 됩니다.\r\n");
      out.write("    function initLayerPosition(){\r\n");
      out.write("        var width = 300; //우편번호서비스가 들어갈 element의 width\r\n");
      out.write("        var height = 400; //우편번호서비스가 들어갈 element의 height\r\n");
      out.write("        var borderWidth = 5; //샘플에서 사용하는 border의 두께\r\n");
      out.write("\r\n");
      out.write("        // 위에서 선언한 값들을 실제 element에 넣는다.\r\n");
      out.write("        element_layer.style.width = width + 'px';\r\n");
      out.write("        element_layer.style.height = height + 'px';\r\n");
      out.write("        element_layer.style.border = borderWidth + 'px solid';\r\n");
      out.write("        // 실행되는 순간의 화면 너비와 높이 값을 가져와서 중앙에 뜰 수 있도록 위치를 계산한다.\r\n");
      out.write("        element_layer.style.left = (((window.innerWidth || document.documentElement.clientWidth) - width)/2 - borderWidth) + 'px';\r\n");
      out.write("        element_layer.style.top = (((window.innerHeight || document.documentElement.clientHeight) - height)/2 - borderWidth) + 'px';\r\n");
      out.write("    }  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("      let idCheck = false;\r\n");
      out.write("      let isAuthcode = false;\r\n");
      out.write("\r\n");
      out.write("      // ID중복체크\r\n");
      out.write("      $(\"#btn_IdCheck\").click(function() {\r\n");
      out.write("\r\n");
      out.write("        if($(\"#mbsp_id\").val() == \"\") {\r\n");
      out.write("          alert(\"아이디를 입력하세요.\");\r\n");
      out.write("          $(\"#mbsp_id\").focus();\r\n");
      out.write("          return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("          url: '/member/idCheck',\r\n");
      out.write("          type: 'get',\r\n");
      out.write("          dataType: 'text',\r\n");
      out.write("          data: {mbsp_id : $(\"#mbsp_id\").val()},\r\n");
      out.write("          success: function(result) {\r\n");
      out.write("\r\n");
      out.write("            if(result == \"yes\") {\r\n");
      out.write("              alert(\"아이디 사용가능\");\r\n");
      out.write("              idCheck = true;\r\n");
      out.write("            }else {\r\n");
      out.write("              alert(\"아이디 사용불가능\");\r\n");
      out.write("              $(\"#mbsp_id\").val(\"\");\r\n");
      out.write("              $(\"#mbsp_id\").focus();\r\n");
      out.write("            }        \r\n");
      out.write("            \r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // 메일인증코드\r\n");
      out.write("      $(\"#btn_authcode\").click(function(){\r\n");
      out.write("        if($(\"#mbsp_email\").val() == \"\") {\r\n");
      out.write("          alert(\"메일주소를 입력하세요.\");\r\n");
      out.write("          $(\"#mbsp_email\").focus();\r\n");
      out.write("          return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("          url: '/email/send',\r\n");
      out.write("          type: 'get',\r\n");
      out.write("          dataType: 'text',  \r\n");
      out.write("          data: {receiverMail : $(\"#mbsp_email\").val() }, \r\n");
      out.write("          success : function(result) {\r\n");
      out.write("            if(result == \"success\") {\r\n");
      out.write("              alert(\"인증메일이 발송되었습니다. 메일 확인해주세요.\");\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      //인증확인\r\n");
      out.write("      $(\"#btn_confirmAuthcode\").click(function() {\r\n");
      out.write("        if($(\"#email_auth_code\").val() == \"\") {\r\n");
      out.write("          alert(\"인증코드를 입력하세요.\");\r\n");
      out.write("          $(\"#email_auth_code\").focus();\r\n");
      out.write("          return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("          url: '/email/confirmAuthcode',\r\n");
      out.write("          type: 'get',\r\n");
      out.write("          dataType: 'text',   \r\n");
      out.write("          data: {authCode : $(\"#email_auth_code\").val() }, \r\n");
      out.write("          success : function(result) {\r\n");
      out.write("            if(result == \"success\") {\r\n");
      out.write("              alert(\"인증코드가 확인 되었읍니다.\");\r\n");
      out.write("              isAuthcode = true;\r\n");
      out.write("            }else if(result == \"fail\") {\r\n");
      out.write("              alert(\"인증코드가 다릅니다. 인증코드 요청을 다시 해주세요.\");   \r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // 회원가입 전송\r\n");
      out.write("      $(\"#btn_join\").click(function() {\r\n");
      out.write("        let joinForm = $(\"#joinForm\");\r\n");
      out.write("\r\n");
      out.write("        // 자바스크립트 유효성검사 코드작업\r\n");
      out.write("\r\n");
      out.write("        joinForm.submit();\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("    }); // jQuery read event end\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/include/header.jsp(36,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginStatus != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  <span>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginStatus.mbsp_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" 님</span> /\r\n");
          out.write("  <span>포인트 : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginStatus.mbsp_point}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </span> /\r\n");
          out.write("  <span>최근접속 : \r\n");
          out.write("  \t");
          if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("   </span>\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/include/header.jsp(40,3) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginStatus.mbsp_lastlogin}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/include/header.jsp(40,3) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd HH:mm");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/include/header.jsp(45,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginStatus == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <a class=\"p-2 text-dark\" href=\"/member/login\">Login</a>\r\n");
          out.write("    <a class=\"p-2 text-dark\" href=\"/member/join\">Join</a>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/include/header.jsp(50,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginStatus != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <a class=\"p-2 text-dark\" href=\"/member/logout\">Logout</a>\r\n");
          out.write("    <a class=\"p-2 text-dark\" href=\"/member/modify\">Modify</a>\r\n");
          out.write("     ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
