/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2023-05-22 08:22:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1527726294253L));
    _jspx_dependants.put("jar:file:/C:/JaeYun/work-space/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mall/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/JaeYun/work-space/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mall/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t<title>Login Page</title>\n");
      out.write("\t\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("$(document).ready(function() {\n");
      out.write("\t$('#signup').click(function() {\n");
      out.write("\t  $('.pinkbox').css('transform', 'translateX(80%)');\n");
      out.write("\t  $('.signin').addClass('nodisplay');\n");
      out.write("\t  $('.signup').removeClass('nodisplay');\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t$('#signin').click(function() {\n");
      out.write("\t  $('.pinkbox').css('transform', 'translateX(0%)');\n");
      out.write("\t  $('.signup').addClass('nodisplay');\n");
      out.write("\t  $('.signin').removeClass('nodisplay');\n");
      out.write("\t});\n");
      out.write("});\t\n");
      out.write("     \n");
      out.write("    $(document).ready(function() {\n");
      out.write("      let msg = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("      if(msg == 'failID') {\n");
      out.write("        alert(\"아이디 확인바람\");\n");
      out.write("        $(\"#mbsp_id\").focus();\n");
      out.write("      }else if(msg == 'failPW') {\n");
      out.write("        alert(\"비밀번호 확인바람\");\n");
      out.write("        $(\"#mbsp_password\").focus();\n");
      out.write("      }\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("@import url(\"https://fonts.googleapis.com/css?family=Open+Sans:300,400|Lora\");\n");
      out.write("body {\n");
      out.write("  background: #CBC0D3;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* div box styling */\n");
      out.write(".container {\n");
      out.write("  margin: auto;\n");
      out.write("  width: 650px;\n");
      out.write("  height: 550px;\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".welcome {\n");
      out.write("  background: #f6f6f6;\n");
      out.write("  width: 650px;\n");
      out.write("  height: 415px;\n");
      out.write("  position: absolute;\n");
      out.write("  top: 25%;\n");
      out.write("  border-radius: 5px;\n");
      out.write("  box-shadow: 5px 5px 5px rgba(0, 0, 0, 0.1);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".pinkbox {\n");
      out.write("  position: absolute;\n");
      out.write("  top: -10%;\n");
      out.write("  left: 5%;\n");
      out.write("  background: #EAC7CC;\n");
      out.write("  width: 320px;\n");
      out.write("  height: 500px;\n");
      out.write("  border-radius: 5px;\n");
      out.write("  box-shadow: 2px 0 10px rgba(0, 0, 0, 0.1);\n");
      out.write("  transition: all 0.5s ease-in-out;\n");
      out.write("  z-index: 2;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nodisplay {\n");
      out.write("  display: none;\n");
      out.write("  transition: all 0.5s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".leftbox, .rightbox {\n");
      out.write("  position: absolute;\n");
      out.write("  width: 50%;\n");
      out.write("  transition: 1s all ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".leftbox {\n");
      out.write("  left: -2%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".rightbox {\n");
      out.write("  right: -2%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* font & button styling */\n");
      out.write("h1 {\n");
      out.write("  font-family: \"Open Sans\", sans-serif;\n");
      out.write("  text-align: center;\n");
      out.write("  margin-top: 95px;\n");
      out.write("  text-transform: uppercase;\n");
      out.write("  color: #f6f6f6;\n");
      out.write("  font-size: 2em;\n");
      out.write("  letter-spacing: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".title {\n");
      out.write("  font-family: \"Lora\", serif;\n");
      out.write("  color: #8E9AAF;\n");
      out.write("  font-size: 1.8em;\n");
      out.write("  line-height: 1.1em;\n");
      out.write("  letter-spacing: 3px;\n");
      out.write("  text-align: center;\n");
      out.write("  font-weight: 300;\n");
      out.write("  margin-top: 20%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".desc {\n");
      out.write("  margin-top: -8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".account {\n");
      out.write("  margin-top: 45%;\n");
      out.write("  font-size: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("p {\n");
      out.write("  font-family: \"Open Sans\", sans-serif;\n");
      out.write("  font-size: 0.7em;\n");
      out.write("  letter-spacing: 2px;\n");
      out.write("  color: #8E9AAF;\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("span {\n");
      out.write("  color: #EAC7CC;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".flower {\n");
      out.write("  position: absolute;\n");
      out.write("  width: 120px;\n");
      out.write("  height: 120px;\n");
      out.write("  top: 46%;\n");
      out.write("  left: 29%;\n");
      out.write("  opacity: 0.7;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".smaller {\n");
      out.write("  width: 90px;\n");
      out.write("  height: 100px;\n");
      out.write("  top: 48%;\n");
      out.write("  left: 38%;\n");
      out.write("  opacity: 0.9;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button {\n");
      out.write("  padding: 12px;\n");
      out.write("  font-family: \"Open Sans\", sans-serif;\n");
      out.write("  text-transform: uppercase;\n");
      out.write("  letter-spacing: 3px;\n");
      out.write("  font-size: 11px;\n");
      out.write("  border-radius: 10px;\n");
      out.write("  margin: auto;\n");
      out.write("  outline: none;\n");
      out.write("  display: block;\n");
      out.write("}\n");
      out.write("button:hover {\n");
      out.write("  background: #EAC7CC;\n");
      out.write("  color: #f6f6f6;\n");
      out.write("  transition: background-color 1s ease-out;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button {\n");
      out.write("  margin-top: 3%;\n");
      out.write("  background: #f6f6f6;\n");
      out.write("  color: #ce7d88;\n");
      out.write("  border: solid 1px #EAC7CC;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* form styling */\n");
      out.write("form {\n");
      out.write("  display: flex;\n");
      out.write("  align-items: center;\n");
      out.write("  flex-direction: column;\n");
      out.write("  padding-top: 7px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".more-padding {\n");
      out.write("  padding-top: 35px;\n");
      out.write("}\n");
      out.write(".more-padding input {\n");
      out.write("  padding: 12px;\n");
      out.write("}\n");
      out.write(".more-padding .submit {\n");
      out.write("  margin-top: 45px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".submit {\n");
      out.write("  margin-top: 25px;\n");
      out.write("  padding: 12px;\n");
      out.write("  border-color: #ce7d88;\n");
      out.write("}\n");
      out.write(".submit:hover {\n");
      out.write("  background: #CBC0D3;\n");
      out.write("  border-color: #bfb1c9;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input {\n");
      out.write("  background: #EAC7CC;\n");
      out.write("  width: 65%;\n");
      out.write("  color: #ce7d88;\n");
      out.write("  border: none;\n");
      out.write("  border-bottom: 1px solid rgba(246, 246, 246, 0.5);\n");
      out.write("  padding: 9px;\n");
      out.write("  margin: 7px;\n");
      out.write("}\n");
      out.write("input::placeholder {\n");
      out.write("  color: #f6f6f6;\n");
      out.write("  letter-spacing: 2px;\n");
      out.write("  font-size: 1.3em;\n");
      out.write("  font-weight: 100;\n");
      out.write("}\n");
      out.write("input:focus {\n");
      out.write("  color: #ce7d88;\n");
      out.write("  outline: none;\n");
      out.write("  border-bottom: 1.2px solid rgba(206, 125, 136, 0.7);\n");
      out.write("  font-size: 1em;\n");
      out.write("  transition: 0.8s all ease;\n");
      out.write("}\n");
      out.write("input:focus::placeholder {\n");
      out.write("  opacity: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("label {\n");
      out.write("  font-family: \"Open Sans\", sans-serif;\n");
      out.write("  color: #ce7d88;\n");
      out.write("  font-size: 0.8em;\n");
      out.write("  letter-spacing: 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".checkbox {\n");
      out.write("  display: inline;\n");
      out.write("  white-space: nowrap;\n");
      out.write("  position: relative;\n");
      out.write("  left: -62px;\n");
      out.write("  top: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=checkbox] {\n");
      out.write("  width: 7px;\n");
      out.write("  background: #ce7d88;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".checkbox input[type=checkbox]:checked + label {\n");
      out.write("  color: #ce7d88;\n");
      out.write("  transition: 0.5s all ease;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("  <div class=\"welcome\">\n");
      out.write("    <div class=\"pinkbox\">\n");
      out.write("      <div class=\"signup nodisplay\">\n");
      out.write("        <h1>register</h1>\n");
      out.write("        <form autocomplete=\"off\">\n");
      out.write("          <input type=\"text\" placeholder=\"username\">\n");
      out.write("          <input type=\"email\" placeholder=\"email\">\n");
      out.write("          <input type=\"password\" placeholder=\"password\">\n");
      out.write("          <input type=\"password\" placeholder=\"confirm password\">\n");
      out.write("          <a href=\"/member/join\" class=\"button submit\">ACCOUNT</a> \n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"signin\">\n");
      out.write("        <h1>sign in</h1>\n");
      out.write("        <!--  \n");
      out.write("        <form id=\"loginForm\" class=\"more-padding\" autocomplete=\"off\" method=\"post\" action=\"/member/login\" >\n");
      out.write("          <input type=\"text\" placeholder=\"username\">\n");
      out.write("          <input type=\"password\" placeholder=\"password\">\n");
      out.write("          <div class=\"checkbox\">\n");
      out.write("            <input type=\"checkbox\" id=\"remember\" /><label for=\"remember\">remember me</label>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <button type=\"submit\" id=\"login\" class=\"button submit\">login</button>\n");
      out.write("        </form>\n");
      out.write("        -->\n");
      out.write("        <form id=\"loginForm\" method=\"post\" action=\"/member/login\">\n");
      out.write("\t\t  <input type=\"text\" name=\"mbsp_id\" placeholder=\"아이디\">\n");
      out.write("\t\t  <input type=\"password\" name=\"mbsp_password\" placeholder=\"비밀번호\">\n");
      out.write("\t\t  <button type=\"submit\">로그인</button>\n");
      out.write("\t\t</form>\n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"leftbox\">\n");
      out.write("      <h2 class=\"title\"><span>BLOOM</span>&<br>BOUQUET</h2>\n");
      out.write("      <p class=\"desc\">pick your perfect <span>bouquet</span></p>\n");
      out.write("      <img class=\"flower smaller\" src=\"https://image.ibb.co/d5X6pn/1357d638624297b.jpg\" alt=\"1357d638624297b\" border=\"0\">\n");
      out.write("      <p class=\"account\">have an account?</p>\n");
      out.write("      <button class=\"button\" id=\"signin\">login</button>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"rightbox\">\n");
      out.write("      <h2 class=\"title\"><span>BLOOM</span>&<br>BOUQUET</h2>\n");
      out.write("      <p class=\"desc\"> pick your perfect <span>bouquet</span></p>\n");
      out.write("      <img class=\"flower\" src=\"https://preview.ibb.co/jvu2Un/0057c1c1bab51a0.jpg\"/>\n");
      out.write("      <p class=\"account\">don't have an account?</p>\n");
      out.write("      <button class=\"button\" id=\"signup\">sign up</button>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write(" </div>\n");
      out.write("<script>\n");
      out.write("    \n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
